### ISSUE TITLE
Allow sign in with phone number?

### ISSUE THREAD

**Issue by joshua-scott** [Camberi/firecms#257]
Hi! I see that most Firebase sign in options are available, but signing in via phone + SMS code is not. In fact, "phone" is commented out in the `FirebaseSignInProvider` type [here](https://github.com/Camberi/firecms/blob/master/src/firebase_app/models/auth.tsx#L12).

Is it possible to allow sign in via phone? If not, what would be required to implement it?

**Comment by fgatti675** [comment]
Hi Joshua!
We didn't implement the phone authentication since we felt it was not as requested as the other methods and it was a bit harder to implement.
If you want to give it a shot, feel free to submit a PR!
You will need to modify the files `useFirebaseAuthDelegate`, `FirebaseAuthDelegate` and `FirebaseLoginView`
To run the CMS locally check these instructions: https://github.com/Camberi/firecms/blob/master/example/README.md 
:)
