### ISSUE TITLE
Feature - provide other types of login

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#26]
It would be awesome to be able to provide other type of login such as email / password. 

We can see the use of `AuthContext` and I am not sure I can "simply" override it in my index.tsx. Nevertheless, it would be nice to have common login providers configured / ready out of the box.

https://github.com/Camberi/firecms/blob/master/src/CMSApp.tsx#L221

<img width="541" alt="image" src="https://user-images.githubusercontent.com/620730/100863757-507be380-3495-11eb-8f52-4b7a9565486d.png">

**Comment by fgatti675** [comment]
Hi @fabarea, this is something we totally have in mind already.
We will need some extra time to develop it since this implies not only creating login with user/password but also registration.

Allowing overriding the auth logic is also a good alternative and we will give it some thought :)

**Comment by faizaand** [comment]
@fgatti675 Where is this auth logic located in the codebase?

**Comment by fgatti675** [comment]
We can probably do a better job at encapsulating the auth flow.
The context that holds Auth state is found in https://github.com/Camberi/firecms/blob/master/src/auth.tsx
Then CMSApp is in charge of handling the login

**Comment by fgatti675** [comment]
I have just moved the auth context and other contexts to:
https://github.com/Camberi/firecms/blob/master/src/contexts/AuthContext.tsx
I've also split CMSApp into smaller components including a LoginView

**Comment by faizanabidnaqvi** [comment]
Just pitching in here. Is it possible to use FirebaseUI for Login/Registration and then the CMSApp can take the Firebase UI Config object as a prop? FirebaseUI is super flexible!

**Comment by faizaand** [comment]
@faizanabidnaqvi I took an attempt at adding what you said in PR #41.

**Comment by fgatti675** [comment]
Hi everyone!
I have merged and adapted the PR by @faizaand into a branch you can checkout here:
https://github.com/Camberi/firecms/tree/firebase-ui
Now we expose the sign in options in the CMSApp entry point so you can choose the ones you need, as specified by FirebaseUI.
It is not my favourite solution, since I would rather implement it myself, and may still do it in the future, but this is providing a lot of flexibility right now.
Feel free to check it out and tell me what you think, I will probably do some more testing and release on npm soon.
Currently the deployed version of the demo is including this update, so you can check it at:
https://firecms-demo-27150.web.app/

**Comment by fgatti675** [comment]
I am closing this since FirebaseUI is now integrated in 0.24.0 :)
