### ISSUE TITLE
Issue with sideEntityController.open() not overwriting schema

### ISSUE THREAD

**Issue by brianpham258** [Camberi/firecms#323]
Hi, I'm setting up a custom side entity view but I couldn't make firecms display the new schema I pass in.
"@camberi/firecms": "^1.0.0"

<img width="427" alt="image" src="https://user-images.githubusercontent.com/43323609/171440698-465ca9d2-77ee-4854-83d3-31ab68a86e43.png">

I set overrideSchemaRegistry = true and passed in the new schema that I want to show, which is articleContentSchema, but instead the side drawer still shown the schema that was defined for the path '/library_items'.

I followed the example code in the file ExampleCMSView.tsx from firecms code base, but I couldn't find where you guys define the path "/products-test"
https://firecms.co/docs/custom_top_level_views/

<img width="461" alt="image" src="https://user-images.githubusercontent.com/43323609/171442023-d5fea87d-a039-4c30-bce1-975b6ef0d7b8.png">

Could someone show me where did I do wrong or how the path "/product-test" was defined?

**Comment by fgatti675** [comment]
Hi @brianpham258 
So that is the intended way to use it.
`products-test` is not defined anywhere else in the example, it just points to the database path.
`overrideSchemaRegistry` should not be necessary.
I understand you have defined a collection with the same path, which is where it's fetching the schema from.
If that's the case it seems to be a bug in the CMS

**Comment by fgatti675** [comment]
If it helps, this issue is already solved in v2.0.0 which is currently in alpha in case you wanna try it out

**Comment by brianpham258** [comment]
Thank you @fgatti675  🙏, let me try the v2

**Comment by fgatti675** [comment]
Hi @brianpham258 did it help?
