### ISSUE TITLE
Get access of parent properties in subcollection

### ISSUE THREAD

**Issue by sebaschartrand** [Camberi/firecms#327]
Hi,

In the schema of a subcollection, how can I retreive the title property of the parent entity to setup the storage path?

In this exemple, I got a Product entity with a Configuration subcollection. In the storagepath of Configuration image property, I need the product title as folder name.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/70615827/172954261-bbf5a83c-8531-4c6e-a5cc-e34811115376.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/70615827/172954600-a7861b43-69a4-4f7e-9bc3-22e2feb1fdaf.png">

Thank you!

**Comment by fgatti675** [comment]
Hi @sebaschartrand 
I am afraid this is not possible at the moment!
The values of the parent entity (or at any other level) are tricky to include in the callback, since they belong in a different context.
We will add, in the next alpha release of V2,  the path of the entity:
https://github.com/Camberi/firecms/commit/71606334b062eb93d73ec8a07d4e3861981d82f7
That will allow you to fetch the parent entity with a little string manipulation and use any value you need.
