### ISSUE TITLE
Sorting results empty collection

### ISSUE THREAD

**Issue by tijnar** [Camberi/firecms#63]
I am getting a "This collection is empty" message when I try to do sorting in the collection field's arrow up and down button. Currently, I am using 0.21.2 version. I tried to update my version greater than 0.21.2 but encounter this error message. Any way to fix this issue?

```
../node_modules/@camberi/firecms/dist/index.modern.js
Module not found: Can't resolve 'react/jsx-runtime' in 'D:\abc\firecms-master\firecms-master\node_modules\@camberi\firecms\dist'
```

**Comment by fgatti675** [comment]
Hi @tijnar
You can get an empty collection when sorting if the values you are sorting for are not present in the database. That is by design in Firestore, we can probably add a message explaining why you get this result. If your values were `null` instead of missing, it would work as you expect.
I really don't know about the error you are having, but probably the easiest way to sort is comparing your config to the one in the example, specially the `package.json` y `tsconfig.json`
https://github.com/Camberi/firecms/tree/master/example
Also keep in mind there has been some API changes so you may want to check the `BREAKING` entries in the [changelog](https://github.com/Camberi/firecms/blob/master/CHANGELOG.md)
