### ISSUE TITLE
[feature] custom onSave implementation

### ISSUE THREAD

**Issue by shelooks16** [Camberi/firecms#69]
Hey!

Is there a way to define custom callback when data is saved/updated? 

Consider a situation when a collection or document are read-only, write operations can be only done server-side.
```
read: true;
write: false;
```

`onSaveSuccess` and `onPreSave`  are hooks around client-side save operation.

For example, custom save operation would let us perform calls to an API to update data.

Something like this defined on Schema maybe?
```
onSave = async ({ newValues }) => {
  await updateData(...)
  // if throws - display snackbar
    
  return newValues;
};
```

**Comment by fgatti675** [comment]
Hi Andrew, for your use case, I would suggest implementing that logic as a Cloud Function. 
You could create an `onUpdate` `onWrite` or `onCreate` function and modify your data as you see fit. The CMS would update the UI automatically since it is always listening for background updates. That way you don't need to implement APIs in the client that are probably better suited in the backend, you don't make multiple calls if multiple windows are opened, you ensure execution...

**Comment by shelooks16** [comment]
I undestard that but unfortunately this is not the use case 😢 

Firecms validates data before it's written to Firestore but it does not prevent someone outside of Firecms to do so - in the app, through public URL, etc. There are security rules, but... data validation for some documents using security rules is simply not feasible. That's why `write` logic is moved to custom backend - to perform custom validation.

**Comment by fgatti675** [comment]
Quick update in case someone is interested.
We are currently working on a way to override the complete datasource implementation, allowing you to add your custom logic and even replace the whole Firestore implementation for a different one.

**Comment by fgatti675** [comment]
It is now possible to override the Firestore implementation in version 1.0.0-beta1 :)
We are working on provinding better examples and docs to show how it can be done

**Comment by shelooks16** [comment]
Thanks for letting me know!
Gonna keep an eye on this :)
